---
- name: install nodejs on centos
  hosts: all
  become: yes
  vars: 
    nodejs_version: nodejs
  tasks:
    - name: install nodejs
      shell: curl -sL https://rpm.nodesource.com/setup_10.x | sudo bash -
    - name: install dotnet
      ansible.builtin.yum:
        name: "{{nodejs_version}}"
        update_cache: yes
        state: present
  