

---
- name: Install tomcat 10 on ubuntu 22
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: create a tomcat group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create a tomcat user
      ansible.builtin.user:
        name: tomcat
        create_home: yes
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present
    - name: extract tomcat 10.1.5
      ansible.builtin.unarchive:
        src: https://www-eu.apache.org/dist/tomcat/tomcat-10/v10.1.5/bin/apache-tomcat-10.1.5.tar.gz
        remote_src: yes
        dest: /opt/tomcat
    - name: create a symbolic link
      ansible.builtin.file:
        src: /opt/tomcat/apache-tomcat-10.1.5
        dest: /opt/tomcat/latest
        state: link
    - name: change permissions
      ansible.builtin.file:
        dest: /opt/tomcat
        recurse: true
        owner: tomcat
        group: tomcat
        state: directory
    - name: add execute permissions to shell files
      ansible.builtin.command: sudo sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'
    - name: Create a systemd unit file
      ansible.builtin.copy:
        src: /home/devops/tomcat/tomcat.service
        dest: /etc/systemd/system/tomcat.service
        owner: tomcat
        group: tomcat
    - name: reload daemon and start tomcat
      ansible.builtin.systemd:
        name: tomcat.service
        daemon_reload: yes
        enabled: yes
        state: started
    - name: create a system unit file
      ansible.builtin.copy:
        src: /home/devops/tomcat/tomcat-users.xml
        dest: /opt/tomcat/latest/conf/tomcat-users.xml  
        owner: tomcat
        group: tomcat
    - name: create a manager copy file
      ansible.builtin.copy:
        src: /home/devops/tomcat/context.xml
        dest: /opt/tomcat/latest/webapps/manager/META-INF/context.xml
        owner: tomcat
        group: tomcat 
    - name: create a host manager copy file
      ansible.builtin.copy:
        src: /home/devops/tomcat/context.xml
        dest: /opt/tomcat/latest/webapps/host-manager/META-INF/context.xml
        owner: tomcat
        group: tomcat   
    - name: restart the tomcat service
      ansible.builtin.service:
        name: tomcat
        state: restarted       