---
- name: Install wildfly on ubuntu 22
  hosts: all
  become: yes
  tasks:
    - name: java installation
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: create a wildfly group
      ansible.builtin.group:
        name: wildfly       
        state: present
    - name: create a wildfly user
      ansible.builtin.user:
        name: wildfly
        create_home: yes
        group: wildfly
        home: /opt/wildfly
        shell: /sbin/nologin
        state: present
    - name: create a file
      ansible.builtin.file:
        dest: /tmp
        state: directory
    - name: download wildfly 
      ansible.builtin.get_url:
        url: https://download.jboss.org/wildfly/16.0.0.Final/wildfly-16.0.0.Final.tar.gz
        dest: /tmp
    - name: extract wildfly
      ansible.builtin.unarchive:
        src: /tmp/wildfly-16.0.0.Final.tar.gz
        dest: /tmp
        remote_src: yes
    - name: copy a file
      ansible.builtin.copy:
        src: /tmp/wildfly-16.0.0.Final/
        dest: /opt/wildfly
        remote_src: yes
    - name: change permissions
      ansible.builtin.file:
        dest: /opt/wildfly
        recurse: true
        owner: wildfly
        group: wildfly
        state: directory
    - name: create a directory
      ansible.builtin.file:
        name: /etc/wildfly
        state: directory
    - name: config copy file
      copy:
        src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.conf
        dest: /etc/wildfly/
        remote_src: yes
    - name: copy a file
      ansible.builtin.copy:
        src: /opt/wildfly/docs/contrib/scripts/systemd/launch.sh
        dest: /opt/wildfly/bin/
        remote_src: yes
    - name: add execute permissions to shell files
      ansible.builtin.command: sudo sh -c 'chmod +x /opt/wildfly/bin/*.sh'
    - name: Create a systemd copy file
      ansible.builtin.copy:
        src: /opt/wildfly/docs/contrib/scripts/systemd/wildfly.service
        dest: /etc/systemd/system/
        remote_src: yes
    - name: reload daemon and start wildfly
      ansible.builtin.systemd:
        name: wildfly.service
        daemon_reload: yes
        enabled: yes
        state: started
    - name: Create a copy file
      ansible.builtin.copy:
        src: /home/devops/wildflyconf/mgmt-users.properties/
        dest: /opt/wildfly/standalone/configuration/mgmt-users.properties
        remote_src: yes
    - name: Create a copy file
      ansible.builtin.copy:
        src: /home/devops/wildflyconf/mgmt-users.properties/
        dest: /opt/wildfly/domain/configuration/mgmt-users.properties
    - name: Create a copy file
      ansible.builtin.copy:
        src: /home/devops/wildflyconf/mgmt-group.properties/
        dest: /opt/wildfly/standalone/configuration/mgmt-group.properties
    - name: Create a copy file
      ansible.builtin.copy:
        src: /home/devops/wildflyconf/mgmt-group.properties/
        dest: /opt/wildfly/domain/configuration/mgmt-group.properties
    - name: create a copy of config file
      ansible.builtin.copy:
        src: /home/devops/wildflyconf/wildfly.conf/
        dest: /etc/wildfly/wildfly.conf
    - name: create a copy of launch file
      ansible.builtin.copy:
        src: /home/devops/wildflyconf/launch.sh/
        dest: /opt/wildfly/bin/launch.sh
    - name: restart systemd wildfly
      ansible.builtin.systemd:
        name: wildfly
        state: restarted
    - name: create a copy of wildfly.service
      ansible.builtin.copy:
        src: /home/devops/wildflyconf/wildfly.service/
        dest: /etc/systemd/system/wildfly.service
    - name: create a directory
      ansible.builtin.file:
        name: /var/run/wildfly/
        state: directory
    - name: change permissions 
      ansible.builtin.file:
        dest: /var/run/wildfly/
        owner: wildfly
        group: wildfly
        state: directory
    - name: reload daemon and restart wildfly
      ansible.builtin.systemd:
        name: wildfly.service
        daemon_reload: yes
        state: restarted  