---
- name: install lamp server on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: update packages and install apache
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: install php packages
      ansible.builtin.apt:
        name:
          - php
          - libapache2-mod-php
          - php-mysql
        state: present
    - name: copy the info.php page
      ansible.builtin.copy:
        src: info.php
        dest: /var/www/html/info.php
    - name: restart apache2
      ansible.builtin.systemd:
        name: apache2
        state: restarted

---
- name: install apache on ubuntu
  hosts: all
  become: yes
  tasks:
   - name: install apache2
     ansible.builtin.apt:
      name: apache2
      update_cache: yes
      state: present
   - name: install php
     ansible.builtin.apt:
       name: php
       state: present
   - name: install libapache2-mod-php
     ansible.builtin.apt:
       name: libapache2-mod-php
       state: present
   - name: php-mysql
     ansible.builtin.apt:
       name: php-mysql
       state: present
   - name: create a file with content
     copy:
       dest: /var/www/html/info.php
       content:   
         <?php
         phpinfo()
         ?>


