---
- name: Install NopCommerce on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: download packeges
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        dest: /tmp
    - name: Install packages
      apt: 
        name: packages-microsoft-prod.deb
        state: present
    - name: install dotnet
      apt:
        name: 
          - apt-transport-https
          - aspnetcore-runtime-7.0
          - nginx
        state: start
        update_cache: yes
    - name: to configure nginx
      copy:
        src: home/devops/QTtraining/Ansible/yamlfiles/task1
        dest: /etc/nginx/sites-available/default   
    - name: create a directory
      file:
        dest: /var/www/nopCommerce
        state: directory
    - name: Download NopCommerce
      unarchive:
        src: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.1/nopCommerce_4.60.1_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce
        remote_src: yes

    - name: Set permissions for nopCommerce files
      file:
        path: /var/www/nopCommerce
        owner: www-data
        group: www-data
        mode: 0755
        state: directory

    - name: Run NopCommerce database setup
      command: dotnet /var/www/nopCommerce/nopCommerce.dll setup
      args:
        chdir: /var/www/nopCommerce
        
    - name: Configure Nginx to serve NopCommerce
      become: yes
      copy:
        dest: /etc/nginx/sites-available/nopCommerce
        content: |
          server {
              listen 80;
              server_name example.com;
              root /var/www/nopCommerce;
              location / {
                  proxy_pass http://127.0.0.1:5000;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection keep-alive;
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
