---
- name: Install NopCommerce on ubuntu
  hosts: all
  become: yes
  tasks:
    - name: create a file
      ansible.builtin.file:
        dest: /tmp
        state: directory
    - name: download packages
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp
    - name: Install packages
      apt: 
        deb: packages-microsoft-prod.deb
        state: present
    - name: install dotnet
      apt:
        name: 
          - apt-transport-https
          - aspnetcore-runtime-7.0
          - nginx
        state: present
        update_cache: yes
    - name: to configure nginx
      copy:
        src: /home/devops/Ansible/yamlfiles/task1/default
        dest: /etc/nginx/sites-available/default  
    - name: create a directory
      file:
        dest: /var/www/nopCommerce
        state: directory
    - name: Download NopCommerce
      unarchive:
        src: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.60.1/nopCommerce_4.60.1_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce
        remote_src: yes
    - name: create directory
      file:
        path:
          - home/devops/var/www/nopCommerce/bin
          - home/devops/var/www/nopCommerce/logs
        state: directory     
    - name: Set permissions for nopCommerce files
      file:
        path: /var/www/nopCommerce
        owner: www-data
        group: www-data
        state: directory
    - name: create nopcommerce service
      copy:
        src: /home/devops/Ansible/yamlfiles/task1/nopCommerce.service
        dest: /etc/systemd/system/nopCommerce.service
    - name: restart nginx
      service:
        name: nginx
        state: restarted